### ISSUE TITLE
Deploy solana program false

### ISSUE THREAD

**Issue by DINHQUANGMINH198** [smartcontractkit/chainlink-solana-demo#5]
```
$ solana program deploy /home/bc_code/chainlink-solana-demo/target/deploy/chainlink_solana_demo.so
Blockhash expired. 5 retries remaining
Blockhash expired. 4 retries remaining
Blockhash expired. 3 retries remaining
Blockhash expired. 2 retries remaining
Blockhash expired. 1 retries remaining
==========================================================================
Recover the intermediate account's ephemeral keypair file with
`solana-keygen recover` and the following 12-word seed phrase:
==========================================================================
crew cigar vicious thrive equip reopen soon park couple rotate space staff
==========================================================================
To resume a deploy, pass the recovered keypair as the
[BUFFER_SIGNER] to `solana program deploy` or `solana write-buffer'.
Or to recover the account's lamports, pass it as the
[BUFFER_ACCOUNT_ADDRESS] argument to `solana program close`.
==========================================================================
Error: Data writes to account failed: Custom error: Max retries exceeded
```

**Comment by bichkhe** [comment]
This error seems  coming from dev solana network.

**Comment by PatrickAlphaC** [comment]
Could you try again? Agreed, it could be a solana issue.

**Comment by DINHQUANGMINH198** [comment]
i have tried many times

**Comment by pappas999** [comment]
Hi @DINHQUANGMINH198 , thanks for raising. We are very close to launching the new OCR2 feeds on Solana devnet, and this old consumer program that uses the existing feeds will then be deprecated. Based on this, we recommend to wait and then use the new feeds once they're on devnet. You can keep an eye out on the progress of the new feeds [on the main repo](https://github.com/smartcontractkit/chainlink-solana), and we'll be sure to update our [docs](https://docs.chain.link/docs/solana/using-data-feeds-solana/) as soon as they're live, including new code samples to use.

Having said that, if you're motivated to do something with pricing data right now, your issue is a Solana issue and not a Chainlink issue, suggest asking in their discord. A quick search of the error shows a number of people asking about it, could be related to not having enough funds in your account.
